version: '2'

services:

  drone-server:
    image: drone/drone:0.8
    container_name: drone-server
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_ORGS=coopengo
      - DRONE_ADMIN=botCoopengo
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${TEST_DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${TEST_DRONE_GITHUB_SECRET}
      - DRONE_GITHUB_PRIVATE_MODE=true
      - DRONE_SECRET=${TEST_DRONE_SECRET}
      - DRONE_HOST=http://drone.coopengo.com
      - DRONE_LETS_ENCRYPT=true
      - DRONE_GITHUB_MERGE_REF=false
    ports:
      - "80:80"
      - "443:443"
    restart: always

  drone-agent-1:
    image: drone/agent:0.8
    container_name: drone-agent-1
    depends_on: [drone-server]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${TEST_DRONE_SECRET}
    restart: always
